version: '3.9'
services:
  web:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@db:5432/dbname
      REDIS_URL: redis://redis:6379/0
      API_KEY: secret_api_key
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@db:5432/dbname
      REDIS_URL: redis://redis:6379/0
      API_KEY: secret_api_key
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery -A app.core.celery_app.celery_app worker --loglevel=INFO
    depends_on:
      - db
      - redis
